### ISSUE TITLE
“Resource retrieve failed: retrieve: OCDoResource response failed” is returned by OCF servers (occasionally)

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#77]
Steps to reproduce the issue:
- Host: Ubuntu 16.04
- Installed the `iotivity-smarthome-demo` snap (see https://github.com/01org/SmartHome-Demo/tree/master/snap)
 
Here is how I proceed:
- Check that the snap is functional (from a browser: http://localhost:8000/api/oic/res or http://localhost:8000/api/system)
- Ran some OCF servers (after cloning the https://github.com/01org/SmartHome-Demo repo locally, or go to `/snap/iotivity-smarthome-demo/current/ocf-servers/js-servers`)
```
   $ nodejs temperature.js &
   $ nodejs motion.js &
   $ nodejs environmental_sensor.js &
```
- Check that whatever I started is listed as a resource: http://localhost:8000/api/oic/res
- Check the values individually (after grabbing the “di”): http://localhost:8000/api/oic/d/?di=<di>
   Things usually run fine at that point (the browser window given me the value of the sensor is very slow though but I don’t know if it’s related at all to our problem).
- Kill the temperature sensor
- Check in http://localhost:8000/api/oic/res that it has indeed disappeared
- Restart it “nodejs temperature.js &”
- Check again in http://localhost:8000/api/oic/res to see if it’s back
- Try to check its value again: http://localhost:8000/api/oic/d/?di=<di>
   => that’s when it virtually always returns this error: “Resource retrieve failed: retrieve: OCDoResource response failed”
 
As an extra tool to using the browser, I have also been testing these using the [`oic-api-tester.js`](https://github.com/01org/iot-rest-api-server/blob/master/test/oic-api-tester.js) tool from the [iot-rest-api-server](https://github.com/01org/iot-rest-api-server) repo. It also returns the same error after killing and restarting an OCF server.
 
Restarting the entire stack (that’s in the snap) usually fixes the issue. I do that by calling `sudo snap disable iotivity-smarthome-demo` and `sudo snap enable iotivity-smarthome-demo`.

**Comment by nagineni** [comment]
@gvancuts 
> Kill the temperature sensor

How you are killing the server? If you are using `kill -9`, it  will not give process a chance to unrgister the resource so the reference might be still around in the stack and causing the issue after restarting the server that register the same resource.

Instead of killing the process, try shutting down the server gracefully from SIGINT (Ctrl-c).

**Comment by gvancuts** [comment]
Yes, I am using `kill`. I'm not using the `-9` parameter however so I believe it defaults to using `SIGTERM`. I can try with `SIGINT` to see if it makes a difference.

Having said that... I'd think it's a valid scenario to have an OCF simply disappearing from the network without any kind of clean-up happening... and perhaps this is where the problem lies here.

**Comment by gvancuts** [comment]
I have just tried to stop the OCF using `kill -SIGINT` and I observed the following:
- http://localhost:8000/api/oic/res did not list the resource anymore (as expected)
- http://localhost:8000/api/oic/d/?di=<di> returned the “Resource retrieve failed: retrieve: OCDoResource response failed” error

I then started the OCF server again and observed the following:
- http://localhost:8000/api/oic/res listed the resource again (as expected)
- http://localhost:8000/api/oic/d/?di=<di> still returned the “Resource retrieve failed: retrieve: OCDoResource response failed” error

**Comment by nagineni** [comment]
> Having said that... I'd think it's a valid scenario to have an OCF simply disappearing from the network without any kind of clean-up happening... and perhaps this is where the problem lies here.

I agree with you and it has to be handle properly in our bindings/iotivity.

**Comment by nagineni** [comment]
> Having said that... I'd think it's a valid scenario to have an OCF simply disappearing from the network > without any kind of clean-up happening... and perhaps this is where the problem lies here.

> I agree with you and it has to be handle properly in our bindings/iotivity.

This case has already been fixed in 1.2.0. I checked with 1.2.0 branch and it is not reproducible.

**Comment by gvancuts** [comment]
Thanks @nagineni .

IIRC you mentionned there were some issues with IoTivity 1.2.0 (I don't recall the details). What is the status on its readiness, could we update our SmartHome-Demo to this soon?

**Comment by nagineni** [comment]
@gvancuts 1.2.0 branch is not fully ready yet. I was waiting for some missing functionality from the bindings (mostly related to the device presence) and a fix has been pushed to iotivity-node Yesterday. I will start making changes in our demo and create a PR soon if I don't notice any other issues.

**Comment by nagineni** [comment]
I am also working on updating REST API server to 1.2.0. I will create PRs for both soon.

**Comment by nagineni** [comment]
> I have just tried to stop the OCF using kill -SIGINT and I observed the following:
> http://localhost:8000/api/oic/res did not list the resource anymore (as expected)
> http://localhost:8000/api/oic/d/?di= returned the “Resource retrieve failed: retrieve: OCDoResource response failed” error
> I then started the OCF server again and observed the following:
> http://localhost:8000/api/oic/res listed the resource again (as expected)
> http://localhost:8000/api/oic/d/?di= still returned the “Resource retrieve failed: retrieve: OCDoResource response failed” error

Retrieve request may fail without device discovery first. So, try doing device discovery before sending retrieve requests.

`http://localhost:8000/api/oic/d/` (atleast once after the server is up and running)
`http://localhost:8000/api/oic/d/?di=<device id>`

**Comment by gvancuts** [comment]
> http://localhost:8000/api/oic/d/ (atleast once after the server is up and running)

Doing this typically returns: "Query parameter "di" is missing". I thought doing ` http://localhost:8000/api/oic/res` would trigger the discovery, is that not the case? (The README.md in the iot-rest-api-server led me to believe that...)

> http://localhost:8000/api/oic/d/?di=<device id>

I'm still getting the same error when doing this *after* a http://localhost:8000/api/oic/d/

**Comment by ichbinblau** [comment]
Hi, @gvancuts @nagineni . Thanks for the fix. I verified it locally and could retrieve the fan sensor again after doing discovery first. 
One more finding from my observation is that the REST service will not close the connection in obs mode even if the resource is already stopped or disconnected. 
The steps I took to make it happen:
1. Start REST api, gateway server and motion server
2. Observe data stream in browser with the url (eg. https://10.239.76.66:8000/api/oic/a/pir?di=34376437-6639-6530-2d34-3332362d3433&obs=1 ), the browser outputs the data updates.
3. Shutdown the ocf server by Ctrl+C. The device disappeared from the resource list as expected.
4. The connection in the browser remains forever without any more outputs. 

Is it possible to close the client connection from the server side if the resource is down?

**Comment by gvancuts** [comment]
Hi @ichbinblau , do you know if that issue still exists now that we've moved to IoTivity 1.2.x?

**Comment by ichbinblau** [comment]
Hi, @gvancuts . I just had a test. I can continue to retrieve request when the ocf server starts again without doing a discovery. I am using ocf server in emulator mode built with iotivity 1.2.x. So I think it is not an issue in iotivity 1.2.x.

**Comment by gvancuts** [comment]
I ran a test on my side too and observed the following:
1. Start an OCF server (in my case I used the environmental sensor)
2. Do a resource discovery (`/oic/res`)
3. Check the OCF server `/a/env?di=<di>`
-> It returns the right values
4. Kill the OCF server (`kill -9`)
5. Re-check the OCF server `/a/env?di=<di>` and I now get the following message `Resource retrieve failed: findResources: unexpected response`
6. Re-start the OCF server
7. Re-check again the OCF server `/a/env?di=<di>` and I still get `Resource retrieve failed: findResources: unexpected response`
8. If I re-do a resource discovery (`/oic/res`), then the OCF server provides the correct value again
I do not need to a device discovery anymore `/oic/d`.

Is this the expected behaviour?

**Comment by uhofemei** [comment]
I'm not sure if bringing the OCF server down using SIGKILL is something the REST API server can recover from. After feedback from me regarding this issue with the demo kit, Babu submitted a PR and changed the code to for all OCF servers to exit gracefully on SIGINT and SIGTERM. What happens if you try to bring the server down using CTRL-C instead?

**Comment by gvancuts** [comment]
I haven't tried with Ctrl-C yet. I wanted to try out the 'harsher' version of that scenario. It can only help the stability if all OCF servers exit cleanly but it's not a valid assumption as OCF servers can disappear at any time without notice. This could happen if the process gets killed (like what I'm doing) but also if the network goes down, etc.

**Comment by gvancuts** [comment]
I'm seeing the same behaviour when using `SIGINT` instead of `SIGKILL`.

One note: the `Resource retrieve failed: findResources: unexpected response` typically comes about 45s after issuing the `/a/env?di=<di>` call. Is this expected?

I'm thinking this issue can now be closed. The only little doubt I have is whether it is expected that querying a specific resource that was restarted gives an error until a resource discovery call has been issued again. @nagineni @poussa , thoughts?

**Comment by uhofemei** [comment]
I believe that is the case. It was explained to me by Babu that the re-discovery of a sensor needs to be triggered if the OCF server has been restarted. He also explained it a little ways up in this thread. You can read about it here: https://github.com/01org/SmartHome-Demo/issues/77#issuecomment-272412004
